### ISSUE TITLE
add new attribute on script section xconv.yaml

### ISSUE THREAD

**Issue by dannRocha** [dannRocha/xconv#1]
new attribute to ignore custom or default global tasks, filters or middleware

```yaml
script:
  ignore:
    - push current tag
  tasks:
    - name: push current tag
      enable: true
      language: sh
      bind: bump
      when: after
      script: |
        CURRENT_TAG=$(xc tag current --format=%V)
        git push origin $CURRENT_TAG
```
