### ISSUE TITLE
add alias command for xconv.yaml tasks

### ISSUE THREAD

**Issue by dannRocha** [dannRocha/xconv#4]
## Description

New feature makes it possible to call tasks from xconv.yaml without the need to bind to an existing command.

```yaml
script:
    tasks:
      - name: push current tag
        enable: true
        language: sh
        bind: bump
        when: after
        alias:  send
        description: push current tag to remote repository
        script: |
          CURRENT_TAG=$(xc tag current --format=%V)
          git push origin $CURRENT_TAG
```
Usage:
```sh
xc send
```
Help:
```sh
NAME:
   send - push current tag to remote repository

USAGE:
  xc send 
```
