### ISSUE TITLE
add support for environment variables

### ISSUE THREAD

**Issue by dannRocha** [dannRocha/xconv#6]
Use the ```${ENV_NAME}``` syntax

```yaml
rule:
  changelog_file: CHANGELOG.md
  active_profile: ${XCONV_ACTIVE_PROFILE}

  profiles:
  - name: alpha profile
    extends: xconv_default
    tag:
      mode: standard
      format: v$version${VERSION_SUFFIX}
```
