### ISSUE TITLE
add support for tags only created by xconv or by default

### ISSUE THREAD

**Issue by dannRocha** [dannRocha/xconv#8]
Ignore all git tags and manage only tags created by xconv. Add boolean field  ```restricted``` in tag ```xconv.yaml```

```yml
tag:
     restricted: true 
     mode: standard
     format: v$version

```
